### PR TITLE
Analyse car state

### PR DESCRIPTION
**Pull request by ysz0507**
Alexander said: "Use sensor data to estimate the activity of a car/vehicle, such as standing still, driving, accelerating/decelerating".

### CODE REVIEW

**Comment by QuentinRG** [comment]
When I try to open one recording from saved recordings, the app crashes and I have this message :
image

**Comment by ysz0507** [comment]
> When I try to open one recording from saved recordings, the app crashes and I have this message : image

Mhh it trys to open the file that it is supposed to open... Are you sure you save the recordings in the correct folder on the phone?

**Comment by QuentinRG** [comment]
Yes I'm sure, however, I have looked at your code and for me it was good, I have nothing to say about it except this bug

**Comment by QuentinRG** [comment]
image

**Pull request merged**
